app = "whatsapp-broadcaster"
primary_region = "gru"
[build]
image = "node:20-alpine"
[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
